import fs from 'node:fs';import {connect,pause,evidenceDir} from './client.mjs';
const tv=await connect(),r="window.__NUVIO_SHARED__['js/ui/navigation/router.js'].Router";
const expression=`(function(){var read=function(k){try{return JSON.parse(localStorage.getItem(k))}catch(e){return null}},h=${r}.routes.home,urls=read('installedAddonUrls'),names=read('installedAddonDisplayNames'),cache=read('addonManifestCacheV2');var list=urls&&urls.profiles&&urls.profiles['1']||[],over=names&&names.profiles&&names.profiles['1']||{};return {build:window.__NUVIO_ENV__&&window.__NUVIO_ENV__.NUVIO_BUILD_LABEL,route:${r}.current,profiles:(read('profiles')||[]).map(function(p){return {id:p.id,name:p.name}}),addonCount:list.length,addons:list.map(function(url){return over[url]||cache&&cache.entries&&cache.entries[url]&&cache.entries[url].addon.name||'Unknown'}),renderedCollectionTitles:Array.from(document.querySelectorAll("#home .uj-row-title")).map(function(n){return n.textContent}),collections:(h.collections||[]).map(function(c){return c.name||c.title}),nextUpLoading:!!h.ujNextUpLoading,items:(h.continueWatchingDisplay||[]).map(function(item){return {title:item.title,nextUp:!!item.isNextUp,hasAired:item.hasAired,season:item.season,episode:item.episode,badge:item.progressStatus}})};})()`;
try {
 let state;for(let i=0;i<60;i++){await pause(1500);state=await tv.eval(expression);if(state.route==='home'&&state.addonCount===8&&state.profiles.some(p=>p.name==='Café')&&!state.nextUpLoading)break;}
 fs.writeFileSync(evidenceDir+'corrections-home.json',JSON.stringify(state,null,2));console.log(JSON.stringify(state,null,2));
 await tv.eval(`${r}.navigate('stream',{itemId:'tt0111161',videoId:'tt0111161',itemType:'movie',itemTitle:'Contrôle des sources',manualSelection:true})`);
 let stream;for(let i=0;i<30;i++){await pause(1000);stream=await tv.eval(`(function(){var s=${r}.routes.stream;return {route:${r}.current,loading:!!s.loading,sources:(s.sourceChips||[]).map(function(c){return c.name}),resultProviders:Array.from(new Set((s.streams||[]).map(function(s){return s.addonName})))}})()`);if(stream.route==='stream'&&stream.sources.length>=2&&!stream.loading)break;}
 fs.writeFileSync(evidenceDir+'corrections-streams.json',JSON.stringify(stream,null,2));console.log(stream);
}finally{try{await tv.eval(`${r}.navigate('home')`)}catch{}tv.close()}
