import {evidenceDir,mediaBaseUrl} from './client.mjs';
import fs from'node:fs';import{connect,pause}from'./client.mjs';
const tv=await connect(),samples=[];const r="window.__NUVIO_SHARED__['js/ui/navigation/router.js'].Router",out=evidenceDir+'media-30minutes.json';
const sample=()=>tv.eval(`(function(){var v=document.querySelector('#player video');return {route:${r}.current,time:v&&v.currentTime,paused:v&&v.paused,ended:v&&v.ended,ready:v&&v.readyState,error:v&&v.error&&v.error.code,width:v&&v.videoWidth,height:v&&v.videoHeight,decoded:v&&v.webkitDecodedFrameCount,dropped:v&&v.webkitDroppedFrameCount,homeImages:document.querySelectorAll('#home img[src]').length,heap:performance.memory&&performance.memory.usedJSHeapSize,events:window.__ujVideoEvents||[]};})()`);
const save=()=>fs.writeFileSync(out,JSON.stringify({protocol:'Synthetic H264/AAC MP4 served temporarily by Mac over LAN, 30 minutes wall-clock after playback starts, element muted for comfort after startup; does not validate external streaming servers.',samples},null,2));
try{
 await tv.eval(`${r}.navigate('player',{streamUrl:'${mediaBaseUrl}/continuous-31min.mp4',playerTitle:'Validation lecture continue',itemType:'movie'})`);
 let first;for(let i=0;i<20;i++){await pause(1500);first=await sample();if(first.time>0.5&&!first.paused)break;}
 if(!first||!first.time||first.paused)throw Error('Playback did not start');
 await tv.eval("(function(){var v=document.querySelector('#player video');window.__ujVideoMutedBefore=v.muted;v.muted=true;window.__ujVideoEvents=[];window.__ujVideoListener=function(e){window.__ujVideoEvents.push({type:e.type,time:v.currentTime,at:Date.now()})};['waiting','stalled','playing','pause','error'].forEach(function(n){v.addEventListener(n,window.__ujVideoListener)});return true})()");const started=Date.now();samples.push({...first,elapsedSeconds:0});save();console.log('Continuous playback started.');
 while(Date.now()-started<1800000){await pause(30000);const value=await sample();value.elapsedSeconds=(Date.now()-started)/1000;samples.push(value);save();if(value.error||value.route!=='player'||value.paused)throw Error('Playback interrupted');if(samples.length%5===0)console.log(JSON.stringify(value));}
 console.log('30 minutes continuous playback completed.');await tv.eval(`(function(){var v=document.querySelector('#player video');if(v){v.muted=!!window.__ujVideoMutedBefore;['waiting','stalled','playing','pause','error'].forEach(function(n){v.removeEventListener(n,window.__ujVideoListener)});}${r}.navigate('home');return true})()`);
}finally{save();try{await tv.eval(`(function(){var v=document.querySelector('#player video');if(v){if(window.__ujVideoMutedBefore!==undefined)v.muted=!!window.__ujVideoMutedBefore;['waiting','stalled','playing','pause','error'].forEach(function(n){v.removeEventListener(n,window.__ujVideoListener)});}delete window.__ujVideoMutedBefore;delete window.__ujVideoListener;delete window.__ujVideoEvents;if(${r}.current==='player')${r}.navigate('home');return true})()`)}finally{tv.close()}}
